# Generated by Django 5.1.2 on 2024-10-16 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_task_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='number',
        ),
    ]
